# Generated by Django 3.1.7 on 2021-03-15 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auct_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_act', models.CharField(max_length=100)),
                ('price_act', models.FloatField()),
                ('picture_act', models.FileField(upload_to='')),
                ('date_act', models.DateTimeField()),
                ('desc_act', models.CharField(max_length=1000)),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment_auct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_commenter', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=400)),
                ('date_comment', models.DateTimeField(default=datetime.datetime(2021, 3, 15, 18, 25, 24, 222460))),
                ('name_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_product', to='auctions.auct_list')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bid', models.CharField(max_length=64)),
                ('price_bid', models.FloatField()),
                ('date_bid', models.DateTimeField()),
                ('name_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.auct_list')),
            ],
        ),
    ]
