# Generated by Django 3.1.7 on 2021-03-15 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auct_list_bid_comment_auct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_auct',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 18, 41, 38, 101502)),
        ),
    ]
