# Generated by Django 3.1.7 on 2021-03-16 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210315_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auct_list',
            name='picture_act',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='comment_auct',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 21, 12, 29, 121835)),
        ),
    ]
