# Generated by Django 3.1.7 on 2021-03-16 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210315_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auct_list',
            name='picture_act',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='comment_auct',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 0, 26, 30, 668766)),
        ),
    ]
